Style/AsciiComments:
  Enabled: false

Style/Encoding:
  Enabled: false

ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/LeadingCommentSpace:
  Enabled: false

AllCops:
  Exclude:
    - 'config.ru'

